# The URL of the site
base_url = "/"
# base_url = "https://vrslev.com"

# The site title
title = "Lev Vereshchagin"

# The default language of the site
default_language = "en"

# Whether to generate a feed file
generate_feeds = true

# The number of articles to include in the feed
feed_limit = 20

# Syntax highlighting
[markdown]
highlight_code = true

highlight_theme = "css"
highlight_themes_css = [
    { theme = "visual-studio-dark", filename = "syntax-theme-dark.css" },
    { theme = "OneHalfLight", filename = "syntax-theme-light.css" },
]
