# The URL of the site
base_url = "https://vrslev.com"

# The site title
title = "Lev Vereshchagin"

# The default language of the site
default_language = "en"

# Whether to generate a feed file
generate_feeds = true

# The number of articles to include in the feed
feed_limit = 20